kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ${APP_NAME}-ingress
  namespace: tekton-pipelines
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - vossnack.nl
      secretName: tekton-webhook-ingres-ssecret #TODO: hmm..
  rules:
    - host: vossnack.nl
      http:
        paths:
          - path: /${APP_NAME}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: ${APP_NAME}-service
                port:
                  number: 3941
---
