apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP_NAME}-volumeclaim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeName: ${APP_NAME}-volume
  storageClassName: "" 

---
